In [1]:
%load_ext nb_black

ModuleNotFoundError: No module named 'nb_black'

# NumPy
https://numpy.org

Библиотека добавляющая удобную поддержку работы с многомерными массивами и матрицами. В ней присутствует большая библиотека высокоуровневых математических функций для операций с ними.

In [2]:
import numpy as np  # подключение библиотеки

## А нужна ли вообще эта библиотека?

In [3]:
arr = np.arange(1000000)  # range like только в numpy
lst = list(range(1000000))

arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [4]:
%time for _ in range(10): arr_2 = arr * 2
%time for _ in range(10): lst_2 = [x * 2 for x in lst]

CPU times: user 20.8 ms, sys: 8.33 ms, total: 29.1 ms
Wall time: 26.1 ms
CPU times: user 452 ms, sys: 99.2 ms, total: 551 ms
Wall time: 550 ms


In [5]:
arr = np.arange(0, 20, 3)  # работает как и range
arr

array([ 0,  3,  6,  9, 12, 15, 18])

In [6]:
# хотим из вектора сделать матрицу -> изменяем размерность
arr = np.arange(20)
matrix = arr.reshape(4, 5)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
matrix.ravel()  # обратно, из матрицы делаем вектор

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
np.arange(32).reshape(4, 2, 4)  # 3х мерная матрица

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [9]:
print(matrix.shape)  # размерность матрицы
print(matrix.ndim)  # размерность пространства
print(matrix.itemsize)  # сколько занимает в памяти один элемент в байтах
print(matrix.size)  # количество элементов

(4, 5)
2
8
20


In [10]:
arr1d = np.array([1.0, 2.7, 3.1])  # вещественные числа
arr1d.dtype, arr1d.itemsize

(dtype('float64'), 8)

In [11]:
arr2d = np.array([[1.0, 2.7, 3.1], (8.3, 3.14, 2.7)])
arr2d

array([[1.  , 2.7 , 3.1 ],
       [8.3 , 3.14, 2.7 ]])

In [12]:
floats = np.linspace(0, 5, 21)  # range но с вещественным шагом
ints = np.arange(21)

print(floats)
print()
print(ints)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.  ]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [13]:
print(ints + floats)
print(ints * 2)
print(ints > 10)
print(ints @ floats)  # векторное умножение

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.   11.25 12.5  13.75
 15.   16.25 17.5  18.75 20.   21.25 22.5  23.75 25.  ]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
[False False False False False False False False False False False  True
  True  True  True  True  True  True  True  True  True]
717.5


In [14]:
ints[ints > 10]  # мы можем сразу посмотреть, где True

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
arr = ints * floats
print(arr)
print(np.where(arr < 25))  # возвращает индексы
print(
    np.where(arr < 25, arr, -1)
)  # возвращает элементы arr, если выполняется условия, иначе -1

[  0.     0.25   1.     2.25   4.     6.25   9.    12.25  16.    20.25
  25.    30.25  36.    42.25  49.    56.25  64.    72.25  81.    90.25
 100.  ]
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),)
[ 0.    0.25  1.    2.25  4.    6.25  9.   12.25 16.   20.25 -1.   -1.
 -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.  ]


In [16]:
np.zeros((3, 3))  # создаем матрицу из вещественных нулей

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((3, 3))  # создаем матрицу из вещественных единиц

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# Генератор псевдослучайных чисел
rand_gen = np.random.default_rng()  # сам генератор

M1 = rand_gen.random((3, 3))
M2 = rand_gen.random((1, 3))
M1, M2

(array([[0.43379696, 0.14085543, 0.29959915],
        [0.73727232, 0.82858337, 0.59643824],
        [0.03448552, 0.09404463, 0.5565382 ]]),
 array([[0.10079703, 0.86461535, 0.95863719]]))

In [19]:
M1.T  # транспонирование матрицы

array([[0.43379696, 0.73727232, 0.03448552],
       [0.14085543, 0.82858337, 0.09404463],
       [0.29959915, 0.59643824, 0.5565382 ]])

In [20]:
M1 * M2  # поэлементное

array([[0.04372545, 0.12178577, 0.28720689],
       [0.07431486, 0.7164059 , 0.57176788],
       [0.00347604, 0.08131243, 0.53351822]])

In [21]:
M1 @ M2.T  # матричное
M1.dot(M2.T)

array([[0.4527181 ],
       [1.36248863],
       [0.61830668]])

## Доступ к элементам

In [22]:
arr = np.arange(100)
matrix = np.arange(100).reshape(10, 10)

In [23]:
arr[0] = 1000
arr[10:20] = -1  # можем сразу изменить срез
arr[::-1]

array([  99,   98,   97,   96,   95,   94,   93,   92,   91,   90,   89,
         88,   87,   86,   85,   84,   83,   82,   81,   80,   79,   78,
         77,   76,   75,   74,   73,   72,   71,   70,   69,   68,   67,
         66,   65,   64,   63,   62,   61,   60,   59,   58,   57,   56,
         55,   54,   53,   52,   51,   50,   49,   48,   47,   46,   45,
         44,   43,   42,   41,   40,   39,   38,   37,   36,   35,   34,
         33,   32,   31,   30,   29,   28,   27,   26,   25,   24,   23,
         22,   21,   20,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
         -1,   -1,    9,    8,    7,    6,    5,    4,    3,    2,    1,
       1000])

In [24]:
matrix[:3]  # строки
matrix[:3, :5]  # строки, столбцы

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [25]:
vec1 = np.arange(0, 10, 2)
vec2 = np.arange(5)
print(vec1)
print(vec2)
print()

h = np.hstack([vec1, vec2])
v = np.vstack([vec1, vec2])
print(h)
print(v)

[0 2 4 6 8]
[0 1 2 3 4]

[0 2 4 6 8 0 1 2 3 4]
[[0 2 4 6 8]
 [0 1 2 3 4]]


# Pandas
https://pandas.pydata.org

Одна из "главных" библиотек для анализа данных, позволяет работать с данными в привычном для нас табличном виде.

Главные структуры данных библиотеки: 
* DataFrame -- таблица
* Series -- столбец / вектор

In [26]:
import pandas as pd

In [27]:
pd.Series(np.arange(10))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [28]:
pd.DataFrame(np.arange(27).reshape(9, 3))

0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14
5  15  16  17
6  18  19  20
7  21  22  23
8  24  25  26

In [29]:
pd.DataFrame(np.arange(27).reshape(9, 3), columns=["First", "Second", "Third"])

First  Second  Third
0      0       1      2
1      3       4      5
2      6       7      8
3      9      10     11
4     12      13     14
5     15      16     17
6     18      19     20
7     21      22     23
8     24      25     26

## Будем работать с реальными табличными данными
https://www.kaggle.com/lava18/google-play-store-apps?select=googleplaystore.csv

In [31]:
with open("googleplaystore.csv", "r") as file:
    for i, line in enumerate(file):
        print(line)
        if i > 4:
            break

App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver

Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up

Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up

"U Launcher Lite – FREE Live Cool Themes, Hide Apps",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up

Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up

Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up



In [32]:
df = pd.read_csv("googleplaystore.csv")

In [33]:
type(df)

pandas.core.frame.DataFrame

In [34]:
df.head()  # возвращает первые n=5 строк

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone   
1     967   14M     500,000+  Free     0       Everyone   
2   87510  8.7M   5,000,000+  Free     0       Everyone   
3  215644   25M  50,000,000+  Free     0           Teen   
4     967  2.8M     100,000+  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

In [35]:
df.tail(2)  # конец

App             Category  \
10839                  The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840  iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating Reviews                Size     Installs  Type Price  \
10839     4.5     114  Varies with device       1,000+  Free     0   
10840     4.5  398307                 19M  10,000,000+  Free     0   

      Content Rating             Genres      Last Updated         Current Ver  \
10839     Mature 17+  Books & Reference  January 19, 2015  Varies with device   
10840       Everyone          Lifestyle     July 25, 2018  Varies with device   

              Android Ver  
10839  Varies with device  
10840  Varies with device

In [36]:
df.describe(include="all")  # статистика по нашей таблице

App Category       Rating Reviews                Size    Installs  \
count    10841    10841  9367.000000   10841               10841       10841   
unique    9660       34          NaN    6002                 462          22   
top     ROBLOX   FAMILY          NaN       0  Varies with device  1,000,000+   
freq         9     1972          NaN     596                1695        1579   
mean       NaN      NaN     4.193338     NaN                 NaN         NaN   
std        NaN      NaN     0.537431     NaN                 NaN         NaN   
min        NaN      NaN     1.000000     NaN                 NaN         NaN   
25%        NaN      NaN     4.000000     NaN                 NaN         NaN   
50%        NaN      NaN     4.300000     NaN                 NaN         NaN   
75%        NaN      NaN     4.500000     NaN                 NaN         NaN   
max        NaN      NaN    19.000000     NaN                 NaN         NaN   

         Type  Price Content Rating Genres    Last Updated  \
count   10840  10841          10840  10841           10841   
unique      3     93              6    120            1378   
top      Free      0       Everyone  Tools  August 3, 2018   
freq    10039  10040           8714    842             326   
mean      NaN    NaN            NaN    NaN             NaN   
std       NaN    NaN            NaN    NaN             NaN   
min       NaN    NaN            NaN    NaN             NaN   
25%       NaN    NaN            NaN    NaN             NaN   
50%       NaN    NaN            NaN    NaN             NaN   
75%       NaN    NaN            NaN    NaN             NaN   
max       NaN    NaN            NaN    NaN             NaN   

               Current Ver Android Ver  
count                10833       10838  
unique                2832          33  
top     Varies with device  4.1 and up  
freq                  1459        2451  
mean                   NaN         NaN  
std                    NaN         NaN  
min                    NaN         NaN  
25%                    NaN         NaN  
50%                    NaN         NaN  
75%                    NaN         NaN  
max                    NaN         NaN

In [37]:
df.shape  # размерность таблицы

(10841, 13)

In [38]:
df.Category  # доступ к колонке

0             ART_AND_DESIGN
1             ART_AND_DESIGN
2             ART_AND_DESIGN
3             ART_AND_DESIGN
4             ART_AND_DESIGN
                ...         
10836                 FAMILY
10837                 FAMILY
10838                MEDICAL
10839    BOOKS_AND_REFERENCE
10840              LIFESTYLE
Name: Category, Length: 10841, dtype: object

In [39]:
type(df.Category)

pandas.core.series.Series

In [40]:
df["Content Rating"]  # df.Content Rating

0          Everyone
1          Everyone
2          Everyone
3              Teen
4          Everyone
            ...    
10836      Everyone
10837      Everyone
10838      Everyone
10839    Mature 17+
10840      Everyone
Name: Content Rating, Length: 10841, dtype: object

In [41]:
df[["App", "Category", "Rating"]]  # несколько колонок

App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   
1                                    Coloring book moana       ART_AND_DESIGN   
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
3                                  Sketch - Draw & Paint       ART_AND_DESIGN   
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   
...                                                  ...                  ...   
10836                                   Sya9a Maroc - FR               FAMILY   
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                             Parkinson Exercices FR              MEDICAL   
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating  
0         4.1  
1         3.9  
2         4.7  
3         4.5  
4         4.3  
...       ...  
10836     4.5  
10837     5.0  
10838     NaN  
10839     4.5  
10840     4.5  

[10841 rows x 3 columns]

In [42]:
df[5:10]  # срез по строкам

App        Category  Rating Reviews  \
5               Paper flowers instructions  ART_AND_DESIGN     4.4     167   
6  Smoke Effect Photo Maker - Smoke Editor  ART_AND_DESIGN     3.8     178   
7                         Infinite Painter  ART_AND_DESIGN     4.1   36815   
8                     Garden Coloring Book  ART_AND_DESIGN     4.4   13791   
9            Kids Paint Free - Drawing Fun  ART_AND_DESIGN     4.7     121   

   Size    Installs  Type Price Content Rating                   Genres  \
5  5.6M     50,000+  Free     0       Everyone             Art & Design   
6   19M     50,000+  Free     0       Everyone             Art & Design   
7   29M  1,000,000+  Free     0       Everyone             Art & Design   
8   33M  1,000,000+  Free     0       Everyone             Art & Design   
9  3.1M     10,000+  Free     0       Everyone  Art & Design;Creativity   

         Last Updated Current Ver   Android Ver  
5      March 26, 2017         1.0    2.3 and up  
6      April 26, 2018         1.1  4.0.3 and up  
7       June 14, 2018    6.1.61.1    4.2 and up  
8  September 20, 2017       2.9.2    3.0 and up  
9        July 3, 2018         2.8  4.0.3 and up

In [43]:
df.Rating == 4.7  # можем сравнить со всеми значениями в колонке

0        False
1        False
2         True
3        False
4        False
         ...  
10836    False
10837    False
10838    False
10839    False
10840    False
Name: Rating, Length: 10841, dtype: bool

In [44]:
df[df.Rating == 4.7]  # вернутся только те записи, которые True для df.Rating == 4.7

App        Category  \
2      U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN   
9                          Kids Paint Free - Drawing Fun  ART_AND_DESIGN   
16          Photo Designer - Write your name with shapes  ART_AND_DESIGN   
22               Superheroes Wallpapers | 4K Backgrounds  ART_AND_DESIGN   
24                           HD Mickey Minnie Wallpapers  ART_AND_DESIGN   
...                                                  ...             ...   
10604                              Florida State Gameday          SPORTS   
10628                     PriorityONE Credit Union of Fl         FINANCE   
10796   Inf VPN - Global Proxy & Unlimited Free WIFI VPN           TOOLS   
10799                                     Fr Daoud Lamei          SOCIAL   
10809              Castle Clash: RPG War and Strategy FR          FAMILY   

       Rating Reviews  Size    Installs  Type Price Content Rating  \
2         4.7   87510  8.7M  5,000,000+  Free     0       Everyone   
9         4.7     121  3.1M     10,000+  Free     0       Everyone   
16        4.7    3632  5.5M    500,000+  Free     0       Everyone   
22        4.7    7699  4.2M    500,000+  Free     0   Everyone 10+   
24        4.7     118   23M     50,000+  Free     0       Everyone   
...       ...     ...   ...         ...   ...   ...            ...   
10604     4.7    1566   26M     50,000+  Free     0       Everyone   
10628     4.7     178   12M      1,000+  Free     0       Everyone   
10796     4.7   61445  7.8M  1,000,000+  Free     0       Everyone   
10799     4.7    2036  6.8M    100,000+  Free     0       Everyone   
10809     4.7  376223   24M  1,000,000+  Free     0       Everyone   

                        Genres    Last Updated Current Ver   Android Ver  
2                 Art & Design  August 1, 2018       1.2.4  4.0.3 and up  
9      Art & Design;Creativity    July 3, 2018         2.8  4.0.3 and up  
16                Art & Design   July 31, 2018         3.1    4.1 and up  
22                Art & Design   July 12, 2018     2.2.6.2  4.0.3 and up  
24                Art & Design    July 7, 2018       1.1.3    4.1 and up  
...                        ...             ...         ...           ...  
10604                   Sports   July 13, 2018      9.19.2    4.1 and up  
10628                  Finance   June 12, 2018     5.9.1.0    5.0 and up  
10796                    Tools   July 26, 2018     1.9.734    4.1 and up  
10799                   Social    May 20, 2018        1.72  4.0.3 and up  
10809                 Strategy   July 18, 2018       1.4.2    4.1 and up  

[499 rows x 13 columns]

In [45]:
df_rating_4_7 = df[df.Rating == 4.7]  # создадим новый df для Rating == 4.7

In [46]:
df_rating_4_7.head()

App        Category  Rating  \
2   U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
9                       Kids Paint Free - Drawing Fun  ART_AND_DESIGN     4.7   
16       Photo Designer - Write your name with shapes  ART_AND_DESIGN     4.7   
22            Superheroes Wallpapers | 4K Backgrounds  ART_AND_DESIGN     4.7   
24                        HD Mickey Minnie Wallpapers  ART_AND_DESIGN     4.7   

   Reviews  Size    Installs  Type Price Content Rating  \
2    87510  8.7M  5,000,000+  Free     0       Everyone   
9      121  3.1M     10,000+  Free     0       Everyone   
16    3632  5.5M    500,000+  Free     0       Everyone   
22    7699  4.2M    500,000+  Free     0   Everyone 10+   
24     118   23M     50,000+  Free     0       Everyone   

                     Genres    Last Updated Current Ver   Android Ver  
2              Art & Design  August 1, 2018       1.2.4  4.0.3 and up  
9   Art & Design;Creativity    July 3, 2018         2.8  4.0.3 and up  
16             Art & Design   July 31, 2018         3.1    4.1 and up  
22             Art & Design   July 12, 2018     2.2.6.2  4.0.3 and up  
24             Art & Design    July 7, 2018       1.1.3    4.1 and up

In [47]:
df_rating_4_7.iloc[0:5]  # получить по порядку

App        Category  Rating  \
2   U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
9                       Kids Paint Free - Drawing Fun  ART_AND_DESIGN     4.7   
16       Photo Designer - Write your name with shapes  ART_AND_DESIGN     4.7   
22            Superheroes Wallpapers | 4K Backgrounds  ART_AND_DESIGN     4.7   
24                        HD Mickey Minnie Wallpapers  ART_AND_DESIGN     4.7   

   Reviews  Size    Installs  Type Price Content Rating  \
2    87510  8.7M  5,000,000+  Free     0       Everyone   
9      121  3.1M     10,000+  Free     0       Everyone   
16    3632  5.5M    500,000+  Free     0       Everyone   
22    7699  4.2M    500,000+  Free     0   Everyone 10+   
24     118   23M     50,000+  Free     0       Everyone   

                     Genres    Last Updated Current Ver   Android Ver  
2              Art & Design  August 1, 2018       1.2.4  4.0.3 and up  
9   Art & Design;Creativity    July 3, 2018         2.8  4.0.3 and up  
16             Art & Design   July 31, 2018         3.1    4.1 and up  
22             Art & Design   July 12, 2018     2.2.6.2  4.0.3 and up  
24             Art & Design    July 7, 2018       1.1.3    4.1 and up

In [48]:
df_rating_4_7.loc[0:5]  # получить по значению

App        Category  Rating  \
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   

  Reviews  Size    Installs  Type Price Content Rating        Genres  \
2   87510  8.7M  5,000,000+  Free     0       Everyone  Art & Design   

     Last Updated Current Ver   Android Ver  
2  August 1, 2018       1.2.4  4.0.3 and up

In [49]:
df_rating_4_7.loc[0:10, ["App", "Reviews"]]  # по значению и индекса и колонок

App Reviews
2  U Launcher Lite – FREE Live Cool Themes, Hide ...   87510
9                      Kids Paint Free - Drawing Fun     121

In [50]:
df_rating_4_7.index

Int64Index([    2,     9,    16,    22,    24,    26,    34,    36,    38,
               45,
            ...
            10459, 10484, 10571, 10576, 10593, 10604, 10628, 10796, 10799,
            10809],
           dtype='int64', length=499)

In [51]:
df_rating_4_7.iloc[0:5, [0, 3]]  # по порядку и индекса и колонок

App Reviews
2   U Launcher Lite – FREE Live Cool Themes, Hide ...   87510
9                       Kids Paint Free - Drawing Fun     121
16       Photo Designer - Write your name with shapes    3632
22            Superheroes Wallpapers | 4K Backgrounds    7699
24                        HD Mickey Minnie Wallpapers     118

In [52]:
df_rating_4_7.at[2, "App"], df_rating_4_7.iat[0, 0]  # получить одно значение

('U Launcher Lite – FREE Live Cool Themes, Hide Apps',
 'U Launcher Lite – FREE Live Cool Themes, Hide Apps')

## Чуть проанализирум данные

### Каких категорий больше в play market?

In [53]:
df.Category.value_counts()  # метод для Series

FAMILY                 1972
GAME                   1144
TOOLS                   843
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         392
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     231
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
LIBRARIES_AND_DEMO       85
AUTO_AND_VEHICLES        85
WEATHER                  82
ART_AND_DESIGN           65
EVENTS                   64
PARENTING                60
COMICS                   60
BEAUTY                   53
1.9                       1
Name: Category, dtype: int64

In [54]:
df.Category.value_counts().index, df.Category.value_counts().values  # атрибуты

(Index(['FAMILY', 'GAME', 'TOOLS', 'MEDICAL', 'BUSINESS', 'PRODUCTIVITY',
        'PERSONALIZATION', 'COMMUNICATION', 'SPORTS', 'LIFESTYLE', 'FINANCE',
        'HEALTH_AND_FITNESS', 'PHOTOGRAPHY', 'SOCIAL', 'NEWS_AND_MAGAZINES',
        'SHOPPING', 'TRAVEL_AND_LOCAL', 'DATING', 'BOOKS_AND_REFERENCE',
        'VIDEO_PLAYERS', 'EDUCATION', 'ENTERTAINMENT', 'MAPS_AND_NAVIGATION',
        'FOOD_AND_DRINK', 'HOUSE_AND_HOME', 'LIBRARIES_AND_DEMO',
        'AUTO_AND_VEHICLES', 'WEATHER', 'ART_AND_DESIGN', 'EVENTS', 'PARENTING',
        'COMICS', 'BEAUTY', '1.9'],
       dtype='object'),
 array([1972, 1144,  843,  463,  460,  424,  392,  387,  384,  382,  366,
         341,  335,  295,  283,  260,  258,  234,  231,  175,  156,  149,
         137,  127,   88,   85,   85,   82,   65,   64,   60,   60,   53,
           1]))

### Средняя длина названия приложения? 

In [55]:
df.App

0           Photo Editor & Candy Camera & Grid & ScrapBook
1                                      Coloring book moana
2        U Launcher Lite – FREE Live Cool Themes, Hide ...
3                                    Sketch - Draw & Paint
4                    Pixel Draw - Number Art Coloring Book
                               ...                        
10836                                     Sya9a Maroc - FR
10837                     Fr. Mike Schmitz Audio Teachings
10838                               Parkinson Exercices FR
10839                        The SCP Foundation DB fr nn5n
10840        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, Length: 10841, dtype: object

In [56]:
df.App.apply(len)

0        46
1        19
2        50
3        21
4        37
         ..
10836    16
10837    32
10838    22
10839    29
10840    45
Name: App, Length: 10841, dtype: int64

In [57]:
df.App.apply(lambda x: len(x.split()))

0         9
1         3
2        10
3         5
4         7
         ..
10836     4
10837     5
10838     3
10839     6
10840     7
Name: App, Length: 10841, dtype: int64

In [58]:
print(
    df.App.apply(lambda x: len(x.split())).mean(),  # средняя
    df.App.apply(lambda x: len(x.split())).median(),  # медиана
    df.App.apply(lambda x: len(x.split())).max(),  # максимальная
    df.App.apply(lambda x: len(x.split())).min(),  # минимальная
    df.App.apply(lambda x: len(x.split())).quantile(0.25),  # квантиль 25%
    df.App.apply(lambda x: len(x.split())).quantile(0.75),  # квантиль 75%
)

3.9280509178120098 3.0 26 1 2.0 5.0


### Сколько всего скачиваний?

In [59]:
df.Installs.head()

0        10,000+
1       500,000+
2     5,000,000+
3    50,000,000+
4       100,000+
Name: Installs, dtype: object

In [60]:
# df.Installs.sum(), sum(df.Installs)

In [61]:
df.Installs.dtype  # -> object, нам нужнен int

dtype('O')

In [62]:
def installsToInt(install):
    install = "".join((i for i in install if i.isnumeric()))
    return int(install) if install else 0


df.Installs = df.Installs.apply(installsToInt)

In [63]:
df.Installs.sum(), sum(df.Installs)

(167633433487, 167633433487)

### Какая в среднем цена на категорию и какая средняя оценка в этой категории 

In [64]:
df.head()

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

  Reviews  Size  Installs  Type Price Content Rating  \
0     159   19M     10000  Free     0       Everyone   
1     967   14M    500000  Free     0       Everyone   
2   87510  8.7M   5000000  Free     0       Everyone   
3  215644   25M  50000000  Free     0           Teen   
4     967  2.8M    100000  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

In [65]:
df.Price.value_counts()

0         10040
$0.99       148
$2.99       129
$1.99        73
$4.99        72
          ...  
$1.75         1
$14.00        1
$4.85         1
$46.99        1
$1.04         1
Name: Price, Length: 93, dtype: int64

In [66]:
df.Price.apply(lambda x: np.float64(0.0) if x == "0" else np.float64(x[1:]))

ValueError: could not convert string to float: 'veryone'

In [67]:
df.Price[df.Price.str.contains("Everyone")]

10472    Everyone
Name: Price, dtype: object

In [68]:
df.Price = df.Price.apply(
    lambda x: np.float64(0.0)
    if x == "0"
    else None
    if x == "Everyone"
    else np.float64(x[1:])
)

In [69]:
target_df = df[["Category", "Price", "Rating"]]
target_df

Category  Price  Rating
0           ART_AND_DESIGN    0.0     4.1
1           ART_AND_DESIGN    0.0     3.9
2           ART_AND_DESIGN    0.0     4.7
3           ART_AND_DESIGN    0.0     4.5
4           ART_AND_DESIGN    0.0     4.3
...                    ...    ...     ...
10836               FAMILY    0.0     4.5
10837               FAMILY    0.0     5.0
10838              MEDICAL    0.0     NaN
10839  BOOKS_AND_REFERENCE    0.0     4.5
10840            LIFESTYLE    0.0     4.5

[10841 rows x 3 columns]

In [70]:
target_df.fillna(0)  # заполнить пропуски 0

Category  Price  Rating
0           ART_AND_DESIGN    0.0     4.1
1           ART_AND_DESIGN    0.0     3.9
2           ART_AND_DESIGN    0.0     4.7
3           ART_AND_DESIGN    0.0     4.5
4           ART_AND_DESIGN    0.0     4.3
...                    ...    ...     ...
10836               FAMILY    0.0     4.5
10837               FAMILY    0.0     5.0
10838              MEDICAL    0.0     0.0
10839  BOOKS_AND_REFERENCE    0.0     4.5
10840            LIFESTYLE    0.0     4.5

[10841 rows x 3 columns]

In [71]:
target_df.Rating.fillna(target_df.Rating.mean())

0        4.100000
1        3.900000
2        4.700000
3        4.500000
4        4.300000
           ...   
10836    4.500000
10837    5.000000
10838    4.193338
10839    4.500000
10840    4.500000
Name: Rating, Length: 10841, dtype: float64

In [72]:
target_df.dropna()  # убрать все строчки с пропусками

Category  Price  Rating
0           ART_AND_DESIGN    0.0     4.1
1           ART_AND_DESIGN    0.0     3.9
2           ART_AND_DESIGN    0.0     4.7
3           ART_AND_DESIGN    0.0     4.5
4           ART_AND_DESIGN    0.0     4.3
...                    ...    ...     ...
10834               FAMILY    0.0     4.0
10836               FAMILY    0.0     4.5
10837               FAMILY    0.0     5.0
10839  BOOKS_AND_REFERENCE    0.0     4.5
10840            LIFESTYLE    0.0     4.5

[9366 rows x 3 columns]

In [73]:
target_df.dropna(inplace=True)  # не вернуть новую таблицу, а сразу заменить в target_df

/home/utnasun/miniconda3/lib/python3.9/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)


In [74]:
target_df.shape

(9366, 3)

In [75]:
target_df.head()

Category  Price  Rating
0  ART_AND_DESIGN    0.0     4.1
1  ART_AND_DESIGN    0.0     3.9
2  ART_AND_DESIGN    0.0     4.7
3  ART_AND_DESIGN    0.0     4.5
4  ART_AND_DESIGN    0.0     4.3

In [76]:
target_df.corr()

Price    Rating
Price   1.000000 -0.021903
Rating -0.021903  1.000000

In [77]:
target_df.drop([0, 1, 2])  # убрать строки с 0, 1, 2 индексом

Category  Price  Rating
3           ART_AND_DESIGN    0.0     4.5
4           ART_AND_DESIGN    0.0     4.3
5           ART_AND_DESIGN    0.0     4.4
6           ART_AND_DESIGN    0.0     3.8
7           ART_AND_DESIGN    0.0     4.1
...                    ...    ...     ...
10834               FAMILY    0.0     4.0
10836               FAMILY    0.0     4.5
10837               FAMILY    0.0     5.0
10839  BOOKS_AND_REFERENCE    0.0     4.5
10840            LIFESTYLE    0.0     4.5

[9363 rows x 3 columns]

In [78]:
target_df.drop("Category", axis=1)  # убрать колонку Category

Price  Rating
0        0.0     4.1
1        0.0     3.9
2        0.0     4.7
3        0.0     4.5
4        0.0     4.3
...      ...     ...
10834    0.0     4.0
10836    0.0     4.5
10837    0.0     5.0
10839    0.0     4.5
10840    0.0     4.5

[9366 rows x 2 columns]

In [79]:
target_df.head()

Category  Price  Rating
0  ART_AND_DESIGN    0.0     4.1
1  ART_AND_DESIGN    0.0     3.9
2  ART_AND_DESIGN    0.0     4.7
3  ART_AND_DESIGN    0.0     4.5
4  ART_AND_DESIGN    0.0     4.3

In [80]:
target_df.groupby(by="Category").mean()

Price    Rating
Category                               
ART_AND_DESIGN       0.096290  4.358065
AUTO_AND_VEHICLES    0.027260  4.190411
BEAUTY               0.000000  4.278571
BOOKS_AND_REFERENCE  0.134157  4.346067
BUSINESS             0.245512  4.121452
COMICS               0.000000  4.155172
COMMUNICATION        0.172835  4.158537
DATING               0.117744  3.970769
EDUCATION            0.115871  4.389032
ENTERTAINMENT        0.053557  4.126174
EVENTS               0.000000  4.435556
FAMILY               1.314677  4.192272
FINANCE              7.553777  4.131889
FOOD_AND_DRINK       0.077798  4.166972
GAME                 0.255570  4.286326
HEALTH_AND_FITNESS   0.152795  4.277104
HOUSE_AND_HOME       0.000000  4.197368
LIBRARIES_AND_DEMO   0.000000  4.178462
LIFESTYLE            6.244841  4.094904
MAPS_AND_NAVIGATION  0.217339  4.051613
MEDICAL              2.980400  4.189143
NEWS_AND_MAGAZINES   0.017082  4.132189
PARENTING            0.191600  4.300000
PERSONALIZATION      0.406879  4.335987
PHOTOGRAPHY          0.278360  4.192114
PRODUCTIVITY         0.202051  4.211396
SHOPPING             0.023025  4.259664
SOCIAL               0.007645  4.255598
SPORTS               0.292194  4.223511
TOOLS                0.283243  4.047411
TRAVEL_AND_LOCAL     0.165885  4.109292
VIDEO_PLAYERS        0.065375  4.063750
WEATHER              0.392400  4.244000

In [81]:
target_df.groupby(by="Category").agg(["min", "median", "mean", "max"])

Price                          Rating                   \
                      min median      mean     max    min median      mean   
Category                                                                     
ART_AND_DESIGN        0.0    0.0  0.096290    1.99    3.2    4.4  4.358065   
AUTO_AND_VEHICLES     0.0    0.0  0.027260    1.99    2.1    4.3  4.190411   
BEAUTY                0.0    0.0  0.000000    0.00    3.1    4.3  4.278571   
BOOKS_AND_REFERENCE   0.0    0.0  0.134157    4.60    2.7    4.5  4.346067   
BUSINESS              0.0    0.0  0.245512   17.99    1.0    4.3  4.121452   
COMICS                0.0    0.0  0.000000    0.00    2.8    4.4  4.155172   
COMMUNICATION         0.0    0.0  0.172835    4.99    1.0    4.3  4.158537   
DATING                0.0    0.0  0.117744    7.99    1.0    4.1  3.970769   
EDUCATION             0.0    0.0  0.115871    5.99    3.5    4.4  4.389032   
ENTERTAINMENT         0.0    0.0  0.053557    4.99    3.0    4.2  4.126174   
EVENTS                0.0    0.0  0.000000    0.00    2.9    4.5  4.435556   
FAMILY                0.0    0.0  1.314677  399.99    1.0    4.3  4.192272   
FINANCE               0.0    0.0  7.553777  399.99    1.0    4.3  4.131889   
FOOD_AND_DRINK        0.0    0.0  0.077798    4.99    1.7    4.3  4.166972   
GAME                  0.0    0.0  0.255570   17.99    1.0    4.4  4.286326   
HEALTH_AND_FITNESS    0.0    0.0  0.152795    7.99    1.4    4.5  4.277104   
HOUSE_AND_HOME        0.0    0.0  0.000000    0.00    2.8    4.3  4.197368   
LIBRARIES_AND_DEMO    0.0    0.0  0.000000    0.00    3.1    4.2  4.178462   
LIFESTYLE             0.0    0.0  6.244841  400.00    1.5    4.2  4.094904   
MAPS_AND_NAVIGATION   0.0    0.0  0.217339   11.99    1.9    4.2  4.051613   
MEDICAL               0.0    0.0  2.980400   79.99    1.0    4.3  4.189143   
NEWS_AND_MAGAZINES    0.0    0.0  0.017082    2.99    1.7    4.2  4.132189   
PARENTING             0.0    0.0  0.191600    4.99    2.0    4.4  4.300000   
PERSONALIZATION       0.0    0.0  0.406879    9.99    2.5    4.4  4.335987   
PHOTOGRAPHY           0.0    0.0  0.278360   19.99    2.0    4.3  4.192114   
PRODUCTIVITY          0.0    0.0  0.202051    8.99    1.0    4.3  4.211396   
SHOPPING              0.0    0.0  0.023025    2.99    1.6    4.3  4.259664   
SOCIAL                0.0    0.0  0.007645    0.99    1.9    4.3  4.255598   
SPORTS                0.0    0.0  0.292194   29.99    1.5    4.3  4.223511   
TOOLS                 0.0    0.0  0.283243   14.99    1.0    4.2  4.047411   
TRAVEL_AND_LOCAL      0.0    0.0  0.165885    8.99    2.2    4.3  4.109292   
VIDEO_PLAYERS         0.0    0.0  0.065375    5.99    1.8    4.2  4.063750   
WEATHER               0.0    0.0  0.392400    6.99    3.3    4.3  4.244000   

                          
                     max  
Category                  
ART_AND_DESIGN       5.0  
AUTO_AND_VEHICLES    4.9  
BEAUTY               4.9  
BOOKS_AND_REFERENCE  5.0  
BUSINESS             5.0  
COMICS               5.0  
COMMUNICATION        5.0  
DATING               5.0  
EDUCATION            4.9  
ENTERTAINMENT        4.7  
EVENTS               5.0  
FAMILY               5.0  
FINANCE              5.0  
FOOD_AND_DRINK       5.0  
GAME                 5.0  
HEALTH_AND_FITNESS   5.0  
HOUSE_AND_HOME       4.8  
LIBRARIES_AND_DEMO   5.0  
LIFESTYLE            5.0  
MAPS_AND_NAVIGATION  4.9  
MEDICAL              5.0  
NEWS_AND_MAGAZINES   5.0  
PARENTING            5.0  
PERSONALIZATION      5.0  
PHOTOGRAPHY          5.0  
PRODUCTIVITY         5.0  
SHOPPING             5.0  
SOCIAL               5.0  
SPORTS               5.0  
TOOLS                5.0  
TRAVEL_AND_LOCAL     5.0  
VIDEO_PLAYERS        4.9  
WEATHER              4.8

In [82]:
target_df.groupby(by="Category").agg(
    {"Price": lambda x: x.quantile(0.75), "Rating": "mean"}
)

Price    Rating
Category                             
ART_AND_DESIGN       0.0000  4.358065
AUTO_AND_VEHICLES    0.0000  4.190411
BEAUTY               0.0000  4.278571
BOOKS_AND_REFERENCE  0.0000  4.346067
BUSINESS             0.0000  4.121452
COMICS               0.0000  4.155172
COMMUNICATION        0.0000  4.158537
DATING               0.0000  3.970769
EDUCATION            0.0000  4.389032
ENTERTAINMENT        0.0000  4.126174
EVENTS               0.0000  4.435556
FAMILY               0.0000  4.192272
FINANCE              0.0000  4.131889
FOOD_AND_DRINK       0.0000  4.166972
GAME                 0.0000  4.286326
HEALTH_AND_FITNESS   0.0000  4.277104
HOUSE_AND_HOME       0.0000  4.197368
LIBRARIES_AND_DEMO   0.0000  4.178462
LIFESTYLE            0.0000  4.094904
MAPS_AND_NAVIGATION  0.0000  4.051613
MEDICAL              0.7425  4.189143
NEWS_AND_MAGAZINES   0.0000  4.132189
PARENTING            0.0000  4.300000
PERSONALIZATION      0.0000  4.335987
PHOTOGRAPHY          0.0000  4.192114
PRODUCTIVITY         0.0000  4.211396
SHOPPING             0.0000  4.259664
SOCIAL               0.0000  4.255598
SPORTS               0.0000  4.223511
TOOLS                0.0000  4.047411
TRAVEL_AND_LOCAL     0.0000  4.109292
VIDEO_PLAYERS        0.0000  4.063750
WEATHER              0.0000  4.244000

<IPython.core.display.Javascript object>

In [83]:
# можно отсортировать
target_df.groupby(by="Category").mean().sort_values(by="Price", ascending=False)

Price    Rating
Category                               
FINANCE              7.553777  4.131889
LIFESTYLE            6.244841  4.094904
MEDICAL              2.980400  4.189143
FAMILY               1.314677  4.192272
PERSONALIZATION      0.406879  4.335987
WEATHER              0.392400  4.244000
SPORTS               0.292194  4.223511
TOOLS                0.283243  4.047411
PHOTOGRAPHY          0.278360  4.192114
GAME                 0.255570  4.286326
BUSINESS             0.245512  4.121452
MAPS_AND_NAVIGATION  0.217339  4.051613
PRODUCTIVITY         0.202051  4.211396
PARENTING            0.191600  4.300000
COMMUNICATION        0.172835  4.158537
TRAVEL_AND_LOCAL     0.165885  4.109292
HEALTH_AND_FITNESS   0.152795  4.277104
BOOKS_AND_REFERENCE  0.134157  4.346067
DATING               0.117744  3.970769
EDUCATION            0.115871  4.389032
ART_AND_DESIGN       0.096290  4.358065
FOOD_AND_DRINK       0.077798  4.166972
VIDEO_PLAYERS        0.065375  4.063750
ENTERTAINMENT        0.053557  4.126174
AUTO_AND_VEHICLES    0.027260  4.190411
SHOPPING             0.023025  4.259664
NEWS_AND_MAGAZINES   0.017082  4.132189
SOCIAL               0.007645  4.255598
LIBRARIES_AND_DEMO   0.000000  4.178462
EVENTS               0.000000  4.435556
COMICS               0.000000  4.155172
BEAUTY               0.000000  4.278571
HOUSE_AND_HOME       0.000000  4.197368

<IPython.core.display.Javascript object>

In [84]:
target_df.groupby(by="Category").agg(["min", "median", "mean", "max"])

Price                          Rating                   \
                      min median      mean     max    min median      mean   
Category                                                                     
ART_AND_DESIGN        0.0    0.0  0.096290    1.99    3.2    4.4  4.358065   
AUTO_AND_VEHICLES     0.0    0.0  0.027260    1.99    2.1    4.3  4.190411   
BEAUTY                0.0    0.0  0.000000    0.00    3.1    4.3  4.278571   
BOOKS_AND_REFERENCE   0.0    0.0  0.134157    4.60    2.7    4.5  4.346067   
BUSINESS              0.0    0.0  0.245512   17.99    1.0    4.3  4.121452   
COMICS                0.0    0.0  0.000000    0.00    2.8    4.4  4.155172   
COMMUNICATION         0.0    0.0  0.172835    4.99    1.0    4.3  4.158537   
DATING                0.0    0.0  0.117744    7.99    1.0    4.1  3.970769   
EDUCATION             0.0    0.0  0.115871    5.99    3.5    4.4  4.389032   
ENTERTAINMENT         0.0    0.0  0.053557    4.99    3.0    4.2  4.126174   
EVENTS                0.0    0.0  0.000000    0.00    2.9    4.5  4.435556   
FAMILY                0.0    0.0  1.314677  399.99    1.0    4.3  4.192272   
FINANCE               0.0    0.0  7.553777  399.99    1.0    4.3  4.131889   
FOOD_AND_DRINK        0.0    0.0  0.077798    4.99    1.7    4.3  4.166972   
GAME                  0.0    0.0  0.255570   17.99    1.0    4.4  4.286326   
HEALTH_AND_FITNESS    0.0    0.0  0.152795    7.99    1.4    4.5  4.277104   
HOUSE_AND_HOME        0.0    0.0  0.000000    0.00    2.8    4.3  4.197368   
LIBRARIES_AND_DEMO    0.0    0.0  0.000000    0.00    3.1    4.2  4.178462   
LIFESTYLE             0.0    0.0  6.244841  400.00    1.5    4.2  4.094904   
MAPS_AND_NAVIGATION   0.0    0.0  0.217339   11.99    1.9    4.2  4.051613   
MEDICAL               0.0    0.0  2.980400   79.99    1.0    4.3  4.189143   
NEWS_AND_MAGAZINES    0.0    0.0  0.017082    2.99    1.7    4.2  4.132189   
PARENTING             0.0    0.0  0.191600    4.99    2.0    4.4  4.300000   
PERSONALIZATION       0.0    0.0  0.406879    9.99    2.5    4.4  4.335987   
PHOTOGRAPHY           0.0    0.0  0.278360   19.99    2.0    4.3  4.192114   
PRODUCTIVITY          0.0    0.0  0.202051    8.99    1.0    4.3  4.211396   
SHOPPING              0.0    0.0  0.023025    2.99    1.6    4.3  4.259664   
SOCIAL                0.0    0.0  0.007645    0.99    1.9    4.3  4.255598   
SPORTS                0.0    0.0  0.292194   29.99    1.5    4.3  4.223511   
TOOLS                 0.0    0.0  0.283243   14.99    1.0    4.2  4.047411   
TRAVEL_AND_LOCAL      0.0    0.0  0.165885    8.99    2.2    4.3  4.109292   
VIDEO_PLAYERS         0.0    0.0  0.065375    5.99    1.8    4.2  4.063750   
WEATHER               0.0    0.0  0.392400    6.99    3.3    4.3  4.244000   

                          
                     max  
Category                  
ART_AND_DESIGN       5.0  
AUTO_AND_VEHICLES    4.9  
BEAUTY               4.9  
BOOKS_AND_REFERENCE  5.0  
BUSINESS             5.0  
COMICS               5.0  
COMMUNICATION        5.0  
DATING               5.0  
EDUCATION            4.9  
ENTERTAINMENT        4.7  
EVENTS               5.0  
FAMILY               5.0  
FINANCE              5.0  
FOOD_AND_DRINK       5.0  
GAME                 5.0  
HEALTH_AND_FITNESS   5.0  
HOUSE_AND_HOME       4.8  
LIBRARIES_AND_DEMO   5.0  
LIFESTYLE            5.0  
MAPS_AND_NAVIGATION  4.9  
MEDICAL              5.0  
NEWS_AND_MAGAZINES   5.0  
PARENTING            5.0  
PERSONALIZATION      5.0  
PHOTOGRAPHY          5.0  
PRODUCTIVITY         5.0  
SHOPPING             5.0  
SOCIAL               5.0  
SPORTS               5.0  
TOOLS                5.0  
TRAVEL_AND_LOCAL     5.0  
VIDEO_PLAYERS        4.9  
WEATHER              4.8

<IPython.core.display.Javascript object>

In [85]:
df.head()

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

  Reviews  Size  Installs  Type  Price Content Rating  \
0     159   19M     10000  Free    0.0       Everyone   
1     967   14M    500000  Free    0.0       Everyone   
2   87510  8.7M   5000000  Free    0.0       Everyone   
3  215644   25M  50000000  Free    0.0           Teen   
4     967  2.8M    100000  Free    0.0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

<IPython.core.display.Javascript object>

In [86]:
target_df_2 = df[["Category", "Price", "Rating", "Content Rating"]]
target_df_2.dropna(inplace=True)
target_df_2

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Category  Price  Rating Content Rating
0           ART_AND_DESIGN    0.0     4.1       Everyone
1           ART_AND_DESIGN    0.0     3.9       Everyone
2           ART_AND_DESIGN    0.0     4.7       Everyone
3           ART_AND_DESIGN    0.0     4.5           Teen
4           ART_AND_DESIGN    0.0     4.3       Everyone
...                    ...    ...     ...            ...
10834               FAMILY    0.0     4.0       Everyone
10836               FAMILY    0.0     4.5       Everyone
10837               FAMILY    0.0     5.0       Everyone
10839  BOOKS_AND_REFERENCE    0.0     4.5     Mature 17+
10840            LIFESTYLE    0.0     4.5       Everyone

[9366 rows x 4 columns]

<IPython.core.display.Javascript object>

In [87]:
target_df_2.groupby(["Category", "Content Rating"]).mean()

Price    Rating
Category          Content Rating                    
ART_AND_DESIGN    Everyone        0.102931  4.346552
                  Everyone 10+    0.000000  4.700000
                  Teen            0.000000  4.466667
AUTO_AND_VEHICLES Everyone        0.028028  4.188732
                  Everyone 10+    0.000000  4.300000
...                                    ...       ...
VIDEO_PLAYERS     Teen            0.000000  4.087500
WEATHER           Everyone        0.414507  4.229577
                  Everyone 10+    0.000000  4.400000
                  Mature 17+      0.000000  4.700000
                  Teen            0.000000  4.450000

[113 rows x 2 columns]

<IPython.core.display.Javascript object>

In [88]:
target_df_2.groupby(["Category", "Content Rating"], as_index=False).mean()

Category Content Rating     Price    Rating
0       ART_AND_DESIGN       Everyone  0.102931  4.346552
1       ART_AND_DESIGN   Everyone 10+  0.000000  4.700000
2       ART_AND_DESIGN           Teen  0.000000  4.466667
3    AUTO_AND_VEHICLES       Everyone  0.028028  4.188732
4    AUTO_AND_VEHICLES   Everyone 10+  0.000000  4.300000
..                 ...            ...       ...       ...
108      VIDEO_PLAYERS           Teen  0.000000  4.087500
109            WEATHER       Everyone  0.414507  4.229577
110            WEATHER   Everyone 10+  0.000000  4.400000
111            WEATHER     Mature 17+  0.000000  4.700000
112            WEATHER           Teen  0.000000  4.450000

[113 rows x 4 columns]

<IPython.core.display.Javascript object>

In [89]:
target_df_2.to_csv("Category_Content.csv")  # сохраним наш результат

<IPython.core.display.Javascript object>

### Сводная таблица

In [90]:
pd.pivot_table(
    target_df_2,
    values=["Price", "Rating"],
    index="Category",
    columns="Content Rating",
    aggfunc=np.mean,
).fillna(0)

Price                                    \
Content Rating      Adults only 18+  Everyone Everyone 10+ Mature 17+   
Category                                                                
ART_AND_DESIGN                  0.0  0.102931     0.000000   0.000000   
AUTO_AND_VEHICLES               0.0  0.028028     0.000000   0.000000   
BEAUTY                          0.0  0.000000     0.000000   0.000000   
BOOKS_AND_REFERENCE             0.0  0.159200     0.000000   0.000000   
BUSINESS                        0.0  0.248796     0.000000   0.000000   
COMICS                          0.0  0.000000     0.000000   0.000000   
COMMUNICATION                   0.0  0.192169     0.000000   0.000000   
DATING                          0.0  0.699000     0.000000   0.089218   
EDUCATION                       0.0  0.125594     0.000000   0.000000   
ENTERTAINMENT                   0.0  0.127949     0.000000   0.332222   
EVENTS                          0.0  0.000000     0.000000   0.000000   
FAMILY                          0.0  1.532502     0.744365   0.999318   
FINANCE                         0.0  6.394608     0.000000   0.000000   
FOOD_AND_DRINK                  0.0  0.084800     0.000000   0.000000   
GAME                            0.0  0.219174     0.253154   0.188649   
HEALTH_AND_FITNESS              0.0  0.169963     0.000000   0.000000   
HOUSE_AND_HOME                  0.0  0.000000     0.000000   0.000000   
LIBRARIES_AND_DEMO              0.0  0.000000     0.000000   0.000000   
LIFESTYLE                       0.0  6.925213     0.000000   0.775556   
MAPS_AND_NAVIGATION             0.0  0.222727     0.000000   0.000000   
MEDICAL                         0.0  2.961502     3.748750   3.996667   
NEWS_AND_MAGAZINES              0.0  0.023920     0.000000   0.076154   
PARENTING                       0.0  0.199583     0.000000   0.000000   
PERSONALIZATION                 0.0  0.467985     0.000000   0.000000   
PHOTOGRAPHY                     0.0  0.294133     0.000000   0.000000   
PRODUCTIVITY                    0.0  0.192017     0.000000   4.290000   
SHOPPING                        0.0  0.029305     0.000000   0.000000   
SOCIAL                          0.0  0.023294     0.000000   0.000000   
SPORTS                          0.0  0.338945     0.000000   0.000000   
TOOLS                           0.0  0.285970     0.000000   0.000000   
TRAVEL_AND_LOCAL                0.0  0.170409     0.000000   0.000000   
VIDEO_PLAYERS                   0.0  0.079242     0.000000   0.000000   
WEATHER                         0.0  0.414507     0.000000   0.000000   

                                                Rating                         \
Content Rating            Teen Unrated Adults only 18+  Everyone Everyone 10+   
Category                                                                        
ART_AND_DESIGN        0.000000     0.0             0.0  4.346552     4.700000   
AUTO_AND_VEHICLES     0.000000     0.0             0.0  4.188732     4.300000   
BEAUTY                0.000000     0.0             0.0  4.287179     0.000000   
BOOKS_AND_REFERENCE   0.000000     0.0             0.0  4.351333     4.460000   
BUSINESS              0.000000     0.0             0.0  4.119064     0.000000   
COMICS                0.000000     0.0             4.2  4.344000     4.450000   
COMMUNICATION         0.000000     0.0             0.0  4.140678     0.000000   
DATING                0.000000     0.0             0.0  4.100000     0.000000   
EDUCATION             0.000000     0.0             0.0  4.385315     4.487500   
ENTERTAINMENT         0.000000     0.0             0.0  4.176923     4.100000   
EVENTS                0.000000     0.0             0.0  4.411111     4.500000   
FAMILY                0.467314     0.0             0.0  4.194157     4.238889   
FINANCE              99.997500     0.0             0.0  4.132602     0.000000   
FOOD_AND_DRINK        0.000000     0.0             0.0  4.147000     4.300000   
GAME                  0.

<IPython.core.display.Javascript object>